// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api.proto

/*
Package api is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

It is generated from these files:
	api.proto
*/
package api

import (
	"context"

	bm "github.com/go-kratos/kratos/pkg/net/http/blademaster"
	"github.com/go-kratos/kratos/pkg/net/http/blademaster/binding"
)
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathCalcPing = "/calc.service.v1.Calc/Ping"
var PathCalcAdd = "/calc/add"

// CalcBMServer is the server API for Calc service.
type CalcBMServer interface {
	Ping(ctx context.Context, req *google_protobuf1.Empty) (resp *google_protobuf1.Empty, err error)

	Add(ctx context.Context, req *AddRequest) (resp *AddResponse, err error)
}

var CalcSvc CalcBMServer

func calcPing(c *bm.Context) {
	p := new(google_protobuf1.Empty)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := CalcSvc.Ping(c, p)
	c.JSON(resp, err)
}

func calcAdd(c *bm.Context) {
	p := new(AddRequest)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := CalcSvc.Add(c, p)
	c.JSON(resp, err)
}

// RegisterCalcBMServer Register the blademaster route
func RegisterCalcBMServer(e *bm.Engine, server CalcBMServer) {
	CalcSvc = server
	e.GET("/calc.service.v1.Calc/Ping", calcPing)
	e.GET("/calc/add", calcAdd)
}
